[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.5"

[[constraint]]
  name = "github.com/masterminds/semver"
  version = "1.3.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"
